### ISSUE TITLE
Hunting dimension will return the player to the wrong dimension if the surface world was replaced.

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Hunting-Dimension#31]
I am using Perfect Spawn in my pack with people starting in the Wasteland from AbyssalCraft but when re-entering the Hunting Dimension it sends me back to world 0 but I ant using world 0 so is there a way with Hunting Dimension that I can set it to send me back to the Wasteland from Abyssalcraft instead of Dim 0?

Thanks Again,

Flame

**Comment by Darkhax** [comment]
Thanks for the report, this is probably a bug. Not sure if it's specifically my mod that is broken, but I will look into it and let you know.

**Comment by ghost** [comment]
Thank you

**Comment by Darkhax** [comment]
This has been fixed, you can get the update here: https://minecraft.curseforge.com/projects/hunting-dimension/files/2618599

Thanks for reporting this!

**Comment by ghost** [comment]
Ok still not working, I go into the portal inside the AbyssalCraft Wasteland and when I re-enter the portal inside the Hunting Dim it takes me back to Overworld Dim 0 when My spawn point and respawn Locations are AbyssalCraft Wasteland for my Default world as I am making a custom pack that does not have anyone respawning in the OverWorld aka DIM 0.
